<?php
/**
 * Class CommonSettings
 */
class CommonSettings {

	function __construct()
	{
		$this->init();
	}

	/**
	 * Hook into the appropriate actions when the class is constructed.
	 */
	public static function init() {
		add_action( 'init', array( __CLASS__, 'settings_cpt_init' ), 0 );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_scripts' ) );
		add_action( 'admin_head', array( __CLASS__, 'required_alt_text' ) );	// Script for validate Alt text from Add media button
		add_filter( 'media_send_to_editor', array( __CLASS__, 'modify_media_insert_string' ), 20, 3 );
	}

	/**
	 * Verifies whether a given attachment has an image MIME type
	 * 
	 * @param int $attachment_id The ID of the attachment to be checked
	 * @return bool True if MIME type is "image"
	 */
	public static function verify_media_is_image( $attachment_id ) {
		// Get the attachment's file type
		$mime_type = get_post_mime_type( $attachment_id );
	
		// Verify it is an image
		if ( strpos( $mime_type, 'image' ) !== false ) {
			return true;
		}
	
		return false;
	}

	/**
	 * Modified the HTML output of media items when they are being added to a post, adding an attribute to the <img> tag for easier access of an image's attribution information as stored in the post's metadata.
	 * 
	 * @param string $html The HTML content, as generated by the media library
	 * @param int $id The ID of the media item
	 * @param object $attachment WP_Attachment object for the given image
	 * @return string HTML output, potentially modified to contain a data-attribution attribute where possible
	 */
	public static function modify_media_insert_string( $html, $id, $attachment ) {
		if( self::verify_media_is_image( $id ) ) {
			$image_attribution = get_post_meta( $id, 'gmr_image_attribution', true ); // Retrieve the Image Attribution
			$html_updated = str_replace( '<img ', '<img data-media-image-attribution="'.$image_attribution.'" ', $html );
			$html_updated = str_replace( 'class="', 'class="media-image-with-attr ', $html_updated );
			return $html_updated;
		}
		return $html;
	}

	public static function required_alt_text() {
		global $typenow, $pagenow;
		if ( in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) { ?>
			<script type="text/javascript">
				jQuery(document).ready(function($){
					jQuery(document).on('click','button.button.insert-media.add_media',function(e){
						setTimeout(function(e){
							var buttonInsertContent = jQuery('.supports-drag-drop[style="position: relative;"] .media-button-insert');
							clickListenerContent = jQuery._data(buttonInsertContent[0], 'events').click[0];
							buttonInsertContent.off('click');
							jQuery('.supports-drag-drop[style="position: relative;"] .media-button-insert').click(function(e){
								var altTextContent = jQuery('#attachment-details-alt-text').val();
								if ( altTextContent  || jQuery('#attachment-details-alt-text').length == 0 )
								{
									jQuery('.supports-drag-drop[style="position: relative;"] .media-button-insert').unbind("click");
									buttonInsertContent.click(clickListenerContent.handler);
									buttonInsertContent.triggerHandler('click');
								} else {
									alert( 'ERROR: Please fill the Alt text.' );
									jQuery('#attachment-details-alt-text').focus();
									return false;
								}
							});
						},1000);
					});
					jQuery('a#set-post-thumbnail').click(function(e){
						setTimeout(function(e){
							var buttonInsertFeature = jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select');
							clickListenerFeature = jQuery._data(buttonInsertFeature[0], 'events').click[0];
							buttonInsertFeature.off('click');
							jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select').click(function(e){
								var altTextFeature = jQuery('#attachment-details-alt-text').val();
								if ( altTextFeature  || jQuery('#attachment-details-alt-text').length == 0 )
								{
									jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select').unbind("click");
									buttonInsertFeature.click(clickListenerFeature.handler);
									buttonInsertFeature.triggerHandler('click');
								} else {
									alert( 'ERROR: Please fill the Alt text.' );
									jQuery('#attachment-details-alt-text').focus();
									return false;
								}
							});
						},500);
					});
				});
				jQuery( document ).ajaxComplete(function(event, xhr, settings) {
					var params = {}, queries, temp, i, l;
					// Split into key/value pairs
					queries = settings.data.split("&");
					// Convert the array of strings into an object
					for ( i = 0, l = queries.length; i < l; i++ ) {
						temp = queries[i].split('=');
						params[temp[0]] = temp[1];
					}
					var data= params;
					if(data.action == 'get-post-thumbnail-html'){
						setTimeout(function(e){
							jQuery('a#set-post-thumbnail').click(function(e){
								setTimeout(function(e){
									var buttonInsertFeatureAjax = jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select');
									clickListenerFeatureAjax = jQuery._data(buttonInsertFeatureAjax[0], 'events').click[0];
									buttonInsertFeatureAjax.off('click');
									jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select').click(function(e){
										var altTextFeatureAjax = jQuery('#attachment-details-alt-text').val();
										if ( altTextFeatureAjax  || jQuery('#attachment-details-alt-text').length == 0 )
										{
											jQuery('.supports-drag-drop[style="position: relative;"] .media-button-select').unbind("click");
											buttonInsertFeatureAjax.click(clickListenerFeatureAjax.handler);
											buttonInsertFeatureAjax.triggerHandler('click');
										} else {
											alert( 'ERROR: Please fill the Alt text.' );
											jQuery('#attachment-details-alt-text').focus();
											return false;
										}
									});
								},500);
							});
						},500);
					}
				});
			</script>
		<?php }
	}

	public static function settings_cpt_init() {

		// Register custom capability for Draft Kings On/Off Setting and Max mega menu
		$roles = [ 'administrator' ];

		foreach ( $roles as $role ) {
			$role_obj = get_role($role);

			if (is_a($role_obj, \WP_Role::class)) {
				$role_obj->add_cap('manage_draft_kings_onoff_setting', false);
				$role_obj->add_cap('manage_max_mega_menu', false);
			}
		}
		add_filter('query_vars', array( __CLASS__, 'add_query_vars'));
		add_filter( 'megamenu_options_capability', array( __CLASS__, 'megamenu_options_capability_callback' ) );
		
		/**
		 * Code for create a author page
		 */
		$author_page			= get_page_by_path( 'authors', OBJECT );
		if (!isset($author_page)) {
			$author_title		= 'Authors';				// Post title
			$author_content		= '';							// Post Description
			$author_template	= 'templates/postslist.php';	// Add template Name Here
			$author_page_exist	= get_page_by_title($author_title);	// Author Exist
			$author_array		= array(
					'post_type'		=> 'page',
					'post_title'	=> $author_title,
					'post_content'	=> $author_content,
					'post_status'	=> 'publish',
					'post_author'	=> 1,
					);
			if (!isset($author_page_exist->ID)) {
				$author_id	= wp_insert_post($author_array);
				if (!empty($author_template)) {
					update_post_meta($author_id, '_wp_page_template', $author_template);
				}
			}
		}

		add_rewrite_rule('^authors/([0-9]+)(?:/page/([0-9]+))?/?', 'index.php?pagename=authors&author_id=$matches[1]&paged=$matches[2]', 'top');
	}

	public static function add_query_vars( $author_query_vars ) {
		$author_query_vars[] = 'author_id';
		return $author_query_vars;
	}

	public static function megamenu_options_capability_callback() {
		return 'manage_max_mega_menu';
	}
	/**
	 * Returns array of post type.
	 *
	 * @return array
	 */
	public static function allow_fontawesome_posttype_list() {
		return (array) apply_filters( 'allow-font-awesome-for-posttypes', array( 'listicle_cpt', 'affiliate_marketing' )  );
	}
	public static function allow_require_feature_img_posttype_list() {
		return (array) apply_filters( 'allow-font-awesome-for-posttypes', array( 'post', 'page', 'listicle_cpt', 'affiliate_marketing' )  );
	}
	public static function allow_sticky_posttype_list() {
		return (array) apply_filters( 'allow-sticky-for-posttypes', array( 'post', 'page', 'tribe_events', 'listicle_cpt', 'affiliate_marketing', 'gmr_gallery', 'gmr_album', 'contest', 'show', 'podcast', 'episode', 'content-kit' ) );
	}

	/**
	 * Enqueues admin scripts and styles.
	 *
	 * @global string $typenow The current type.
	 * @global string $pagenow The current page.
	 */
	public static function enqueue_scripts() {
		global $typenow, $pagenow;
		$postfix = ( defined( 'SCRIPT_DEBUG' ) && true === SCRIPT_DEBUG ) ? '' : '.min';

		wp_register_style('additional-admin-style', GENERAL_SETTINGS_CPT_URL . "assets/css/register_admin_scripts" . $postfix . ".css", array(), '1.0.0', 'all');
		wp_enqueue_style('additional-admin-style');

		if ( in_array( $typenow, CommonSettings::allow_fontawesome_posttype_list() ) && in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) {
			wp_register_style('general-font-awesome',GENERAL_SETTINGS_CPT_URL . "assets/css/general-font-awesome". $postfix .".css", array(), GENERAL_SETTINGS_CPT_VERSION, 'all');
			wp_enqueue_style('general-font-awesome');
		}

		if ( in_array( $typenow, CommonSettings::allow_require_feature_img_posttype_list() ) && in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) {
			wp_register_script(
					'required-feature-img-admin-js',
					GENERAL_SETTINGS_CPT_URL . "assets/js/require-featured-image-onedit". $postfix .".js",
					array( 'jquery' ), '0.1' );
			// wp_register_script( 'required-feature-img-admin-js', GENERAL_SETTINGS_CPT_URL . "assets/js/require-featured-image-onedit.js", array( 'jquery' ) );
			wp_enqueue_script( 'required-feature-img-admin-js' );

			wp_localize_script(
					'required-feature-img-admin-js',
					'passedFromServer',
					array(
							'jsWarningHtml' => __( '<strong>This entry has no featured image.</strong> Please set one. You need to set a featured image before publishing.', 'require-featured-image' ),
					)
			);
		}

		if ( in_array( $typenow, CommonSettings::allow_sticky_posttype_list() ) && in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) {
			
			wp_register_style('sticky-public-box-css',GENERAL_SETTINGS_CPT_URL . "assets/css/sticky-public-box". $postfix .".css", array(), GENERAL_SETTINGS_CPT_VERSION, 'all');
			wp_enqueue_style('sticky-public-box-css');

			wp_register_script(
				'sticky-public-box-js',
				GENERAL_SETTINGS_CPT_URL . "assets/js/sticky-public-box". $postfix .".js",
				array( 'jquery' ), '0.1' );
			wp_enqueue_script( 'sticky-public-box-js' );

		}

	}
}

// CommonSettings::init();
new CommonSettings();